draw_config:
  append_colon_to_layer_header: true
  arc_radius: 6.0
  arc_scale: 1.0
  combo_h: 26.0
  combo_w: 28.0
  inner_pad_h: 2.0
  inner_pad_w: 2.0
  key_h: 56.0
  dark_mode: true
  key_rx: 6.0
  key_ry: 6.0
  key_w: 60.0
  line_spacing: 1.2
  outer_pad_h: 56.0
  outer_pad_w: 30.0
  small_pad: 2.0
  split_gap: 30.0
parse_config:
  qmk_keycode_map:
    KC_1:
      t: "1"
      s: "!"
    KC_2:
      t: "2"
      s: "@"
    KC_3:
      t: "3"
      s: "#"
    KC_4:
      t: "4"
      s: "$"
    KC_5:
      t: "5"
      s: "%"
    KC_6:
      t: "6"
      s: "^"
    KC_7:
      t: "7"
      s: "&"
    KC_8:
      t: "8"
      s: "*"
    KC_9:
      t: "9"
      s: "("
    KC_0:
      t: "0"
      s: ")"
    KC_EQUAL:
      t: "="
      s: "+"
    KC_MINUS:
      t: "-"
      s: "_"
    KC_SLSH:
      t: "/"
      s: "?"
    KC_FSLH:
      t: "/"
      s: "?"
    KC_BACKSLASH:
      t: '\'
      s: '|'
    KC_BSLH:
      t: '\'
      s: '|'
    KC_SCLN:
      t: ";"
      s: ":"
    KC_SINGLE_QUOTE:
      t: "'"
      s: '"'
    KC_SQT:
      t: ''''
      s: '"'
    KC_APOSTROPHE:
      t: ''''
      s: '"'
    KC_APOS:
      t: ''''
      s: '"'
    KC_COMM:
      t: ","
      s: "<"
    KC_PERIOD:
      t: "."
      s: ">"
    KC_DOT:
      t: "."
      s: ">"
    KC_LEFT_BRACKET:
      t: "["
      s: "{"
    KC_LBKT:
      t: "["
      s: "{"
    KC_RIGHT_BRACKET:
      t: "]"
      s: "}"
    KC_RBKT:
      t: "]"
      s: "}"
    KC_GRAVE:
      t: "`"
      s: "~"